SELECT COUNT(FISH_INFO.ID) AS FISH_COUNT, FISH_NAME_INFO.FISH_NAME
FROM FISH_NAME_INFO, FISH_INFO
WHERE FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_NAME
ORDER BY COUNT(FISH_INFO.ID) DESC